node:
  restart: always
  image: vanessa/nodedcm
  volumes:
    - .:/code

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
    - "443:443"
    - "401:401"
    - "2761:2761"
    - "2762:2762"
    - "11112:11112"
  volumes_from:
    - node
  links:
    - node
